name: Python package

on:
  push:

jobs:
  build-wheels:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: pypa/cibuildwheel@v2.12.3
      env:
        # skip pypy 3.7 and 3.8 as numpy does not support it
        CIBW_SKIP: cp36-* pp37-* pp38-*
        CIBW_ARCHS_WINDOWS: auto64
        CIBW_BEFORE_ALL_MACOS: "brew install llvm libomp"
        CIBW_ENVIRONMENT_MACOS: CC="clang" CXX="clang++" PATH="/usr/local/opt/llvm/bin:$PATH" LDFLAGS="-L/usr/local/opt/llvm/lib" CPPFLAGS="-I/usr/local/opt/llvm/include"
        CIBW_BEFORE_BUILD_MACOS: "clang --version"
        CIBW_BUILD_VERBOSITY: 1
    - uses: actions/upload-artifact@v3
      with:
        path: ./wheelhouse/*.whl
