# 
# Supported 3rd party indices are: FaissIndexFlatL2, FaissIndexBinaryFlat, AnnoyL2, AnnoyManhattan, AnnoyHamming, SKLearnL2
# This allow comparing VPTree indices to thow 3 third party indices.
benchmarks:
- cases:
  - name: "Pyvptree Indexes Comparison"
    k: [2, 4, 8]
    num_queries: [16, 32, 128]
    dataset:
    - total_size: 2500000
    - num_clusters: 50
    index_types:
    - VPTreeL2Index
    - VPTreeBinaryIndex
    - VPTreeChebyshevIndex
    - VPTreeL1Index # (manhattan distance)
  - name: "L2 Comparison"
    k: 8
    num_queries: 16
    dataset:
    - dimensions: [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
    - total_size: 2500000
    - num_clusters: 50
    index_types:
    - FaissIndexFlatL2
    - VPTreeL2Index
    - AnnoyL2
    - SKLearnL2
  - name: "Binary Index Comparison"
    k: 8
    num_queries: 16
    dataset:
    - dimensions: [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
    - total_size: 2500000
    - num_clusters: 50
    index_types:
    - FaissIndexBinaryFlat
    - AnnoyHamming
    - VPTreeBinaryIndex
  - name: "Manhattan Index Comparison"
    k: 8
    num_queries: 16
    dataset:
    - dimensions: [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
    - total_size: 2500000
    - num_clusters: 50
    index_types:
    - AnnoyManhattan
    - VPTreeL1Index

